// <auto-generated />
using EmlakPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmlakPortal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208001237_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmlakPortal.Models.Ev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IlanDurumId")
                        .HasColumnType("int");

                    b.Property<int>("IlanTurId")
                        .HasColumnType("int");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IlanDurumId");

                    b.HasIndex("IlanTurId");

                    b.ToTable("Evler");
                });

            modelBuilder.Entity("EmlakPortal.Models.IlanDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IlanDurumlari");
                });

            modelBuilder.Entity("EmlakPortal.Models.IlanTur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IlanTurleri");
                });

            modelBuilder.Entity("EmlakPortal.Models.Ev", b =>
                {
                    b.HasOne("EmlakPortal.Models.IlanDurum", "IlanDurum")
                        .WithMany("Evler")
                        .HasForeignKey("IlanDurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmlakPortal.Models.IlanTur", "IlanTur")
                        .WithMany("Evler")
                        .HasForeignKey("IlanTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IlanDurum");

                    b.Navigation("IlanTur");
                });

            modelBuilder.Entity("EmlakPortal.Models.IlanDurum", b =>
                {
                    b.Navigation("Evler");
                });

            modelBuilder.Entity("EmlakPortal.Models.IlanTur", b =>
                {
                    b.Navigation("Evler");
                });
#pragma warning restore 612, 618
        }
    }
}
